name: ci

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Download modules
        run: go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.8.0
          args: --timeout=3m

      - name: Run tests
        run: go test ./...
